### ISSUE TITLE
Can't configure Plugin

### ISSUE THREAD

**Issue by NoelBradford** [kyleladd/OSTicket-Trello-Plugin#2]
Hi there, 
Found this plugin - it could well be the solution I have been looking for but it won't let me configure it even after I have enabled it.

<img width="980" alt="screen shot 2017-12-25 at 11 08 09" src="https://user-images.githubusercontent.com/8930657/34338802-0142e068-e964-11e7-81cd-226f2fcbd50b.png">

Generates :- 

[DELETE `ost_lock`.* FROM `ost_lock` WHERE `ost_lock`.`expire` 
 ---- Backtrace ----
 #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1175', '[DELETE `ost_lo...')
 #1 (root)/include/class.orm.php(3133): db_query('DELETE `ost_loc...', true, true)
 #2 (root)/include/class.orm.php(1296): MySqlExecutor->execute()
 #3 (root)/include/class.lock.php(147): QuerySet->delete()
 #4 (root)/include/class.cron.php(33): Lock::cleanup()
 #5 (root)/include/class.cron.php(101): Cron::TicketMonitor()
 #6 (root)/include/api.cron.php(19): Cron::run()
 #7 (root)/include/api.cron.php(40): CronApiController->run()
 #8 (root)/api/cron.php(23): LocalCronApiController::call()
 #9 {main}

What did i miss?

**Comment by jresclapez** [comment]
Hi Noel

Could you fix this error?

The exact same thing happens on my server when I enable the Trello Plugin

Thank you very much

**Comment by jresclapez** [comment]
> Hi there, Found this plugin - it could well be the solution I have been looking for but it won't let me configure it even after I have enabled it.
> 
> <img alt="screen shot 2017-12-25 at 11 08 09" width="980" src="https://user-images.githubusercontent.com/8930657/34338802-0142e068-e964-11e7-81cd-226f2fcbd50b.png">
> 
> Generates :-
> 
> [DELETE `ost_lock`.* FROM `ost_lock` WHERE `ost_lock`.`expire` ---- Backtrace ---- #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1175', '[DELETE `ost_lo...') #1 (root)/include/class.orm.php(3133): db_query('DELETE `ost_loc...', true, true) #2 (root)/include/class.orm.php(1296): MySqlExecutor->execute() #3 (root)/include/class.lock.php(147): QuerySet->delete() #4 (root)/include/class.cron.php(33): Lock::cleanup() #5 (root)/include/class.cron.php(101): Cron::TicketMonitor() #6 (root)/include/api.cron.php(19): Cron::run() #7 (root)/include/api.cron.php(40): CronApiController->run() #8 (root)/api/cron.php(23): LocalCronApiController::call() #9 {main}
> 
> What did i miss?




Could you fix this error?

The exact same thing happens on my server when I enable the Trello Plugin

Thank you very much
